### ISSUE TITLE
Improve the doc please

### ISSUE THREAD

**Issue by jartaud** [hyn-me/multi-tenant#1]

**Comment by Luceos** [comment]
Hello @jartaud any specific direction you are missing documentation for? The package is currently heavily under development so extensive documentation at this time is futile because the package is not yet definitive.

**Comment by Luceos** [comment]
Seeing the current state of this package it is quite possible that an artisan command will follow the following few days to help in the final step of setting up the first website, tenant and hostname and possibly configure the webserver. Once that is done, the documentation can be updated to match these improvements.
Does that help you at this time?

**Comment by jartaud** [comment]
@Luceos Maybe I should wait for new updates like artisan commands.

**Comment by Luceos** [comment]
Ok no problem. You can sign up for the newsletter on http://hyn.me to keep informed about progress. Updates are send once monthly at the max. Or you can wait for me to implement this feature and I have a chance to close this issue.

Thanks for the clarification.

**Comment by jartaud** [comment]
Thanks! i've already signed up :smile:

**Comment by Luceos** [comment]
You can view the last newsletter online at: http://createsend.com/t/i-DF3804D900B40094

**Comment by Luceos** [comment]
Docs are extended immensily since this report. Also chat support is now available through gitter.im. Please see the readme.md for more information.
