### ISSUE TITLE
Class name must be an valid object or string

### ISSUE THREAD

**Issue by Arnout6** [hyn-me/multi-tenant#14]
Hello,

When i run the setup with:
sudo php artisan multi-tenant:setup --tenant=tenant
--email=info@tenant.com --hostname=tenant.com --webserver=apache

I got the following error:

Class name must be an valid object or string in /mt/vendor/hyn-me/webserver/src/HynMe/Webserver/Generators/AbstractFileGenerator.php on line 161

**Comment by Luceos** [comment]
you can use `composer update hyn-me/framework dev-master` to fix this issue for now
