### ISSUE TITLE
Error configuring the webserver

### ISSUE THREAD

**Issue by jartaud** [hyn-me/multi-tenant#16]
Env: ubuntu 15.04
When i issue 
```php sudo php artisan multi-tenant:setup --tenant=mysupertenant --email=admin@mysupertenant.com --hostname=mysupertenant.com --webserver=apache ```

it throws:
```php apache2: Syntax error on line 219 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/sites-enabled/7e7cd5ec51.conf: Could not open config directory /home/MYBOX/Projects/supertenant/storage/webserver/apache: No such file or directory
Configuration succesful```

**Comment by jartaud** [comment]
I've manually created storage/webserver/apache and
```php sudo php artisan multi-tenant:setup --tenant=mysupertenant-n   --email=admin@mysupertenant.com --hostname=mysupertenant.com --webserver=apache``` runs smoothly but not creating the Unix user neither the DB's.

**Comment by Luceos** [comment]
weird, did you set up the queue runner? Try `php artisan queue:work`.. didn't document that yet I now remember.

**Comment by jartaud** [comment]
Thanks for your help.  I enabled ```a2enmod headers```, manually created supertenant/log and running ```[sudo] php artisan queue:work``` results in something like this: 
```adduser: Please enter a username matching the regular expression configured via the NAME_REGEX[_SYSTEM] configuration variable.  Use the --force-badname option to relax this check or reconfigure NAME_REGEX.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Syntax OK
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message

[ErrorException]                                                                                                                                                  
  file_put_contents(/home/MYBOX/Projects/mysupertenant/storage/webserver/nginx/1-mysuperten.conf): failed to open stream: No such file or directory.```

**Comment by Luceos** [comment]
I updated the webserver package, it seemed the webserver directory was not created before setup.

**Comment by jartaud** [comment]
Thanks i'll test it again tonight. By the way i've specified ```--webserver=apache``` but the error keeps pointed to nginx: 
```[ErrorException] file_put_contents(/home/MYBOX/Projects/mysupertenant/storage/webserver/nginx/1-mysuperten.conf): failed to open stream: No such file or directory.```

**Comment by jartaud** [comment]
Homestead on Windows 8.1:

It seems that access is being denied for "sudo", so i use root level and everything ran successfuly. But, nginx will not start throwing: ```nginx: [emerg] unexpected "{" in /home/vagrant/Code/mysupertenant/storage/webserver/nginx/1-mysuperten.conf:46```.

This is the line 46: ``{% if website.directory.media() %}``

I'll test on my pure ubuntu box tonight.

**Comment by Luceos** [comment]
That's a twig template statement, it should be blade.. So I missed two if statements that should have been in blade style. Also the reason you're getting this error is that all configurations are always written, so you can easily switch from webserver or migrate your install to a different machine with a different webservice.

I pushed a new version of webserver, hope this fixes all issues.

**Comment by jartaud** [comment]
Homestead win8.1 php5-fpm + nginx.
Thanks! the configuration is working great. I've set up 2 sites, one is throwing ``502 Bad Gateway``.

I'll test in a box using php5 + apache2.

**Comment by Luceos** [comment]
hi @jartaud i'm setting up vagrant/homestead to start using that as well. Bad gateway is an issue with php fpm, I'm not sure how compatible hyn is with homestead at this time.

**Comment by jartaud** [comment]
Seems working on ubuntu 15 running apache2+php5, but the tenants keep using the main DB, main routes, etc...

**Comment by Luceos** [comment]
OK a little checklist:
- `HynMe\Framework\FrameworkServiceProvider` is registered
- tenant routes.php in `storage/multi-tenant/<id>-<mysupertenant1>`/
- did you register mysupertenant1.com as hostname for the tenant website?

**Comment by jartaud** [comment]
I'm not getting your last point. 
``sudo php artisan multi-tenant:setup --tenant=mysupertenant1 --email=admin@mysupertenant1.com --hostname=mysupertenant1.com --webserver=apache``

and then (as root) `php artisan queue:listen`

If i delete `resources/views/home.blade.php`,  `http://mysupertenant1.com` points to `mysupertenant1/views/home.blade.php`

**Comment by Luceos** [comment]
So the global view is preferred over the tenant view..? I'm not sure whether that is a bad thing.. Or it should be selectable per tenant website perhaps?

**Comment by jartaud** [comment]
I think if i define a view in a tenant, that view should be used instead of the main one. Or maybe i'm not getting the point of having a views folder in the tenant.

Also, ``sudo php artisan multi-tenant:setup`` is creating a DB per tenant but why `http://mysupertenant1.com` keeps using the global DB?

**Comment by Luceos** [comment]
Can you create a route for you tenant and see if `dd(\DB::getConnections())` has a tenant connection?

**Comment by jartaud** [comment]
"mysql" => MySqlConnection {#131 ▼
    #pdo: PDO {#132 ▶}
    #readPdo: null
    #reconnector: Closure {#135 ▶}
    #queryGrammar: MySqlGrammar {#133 ▶}
    #schemaGrammar: null
    #postProcessor: MySqlProcessor {#134}
    #events: Dispatcher {#5 ▶}
    #fetchMode: 8
    #transactions: 0
    #queryLog: []
    #loggingQueries: false
    #pretending: false
    #database: "MAIN_DB"
    #doctrineConnection: null
    #tablePrefix: ""
    #config: array:10 [▶]
  }
  "hyn" => MySqlConnection {#361 ▼
    #pdo: PDO {#362 ▶}
    #readPdo: null
    #reconnector: Closure {#365 ▶}
    #queryGrammar: MySqlGrammar {#363 ▶}
    #schemaGrammar: null
    #postProcessor: MySqlProcessor {#364}
    #events: Dispatcher {#5 ▶}
    #fetchMode: 8
    #transactions: 0
    #queryLog: []
    #loggingQueries: false
    #pretending: false
    #database: "MAIN_DB"
    #doctrineConnection: null
    #tablePrefix: ""
    #config: array:10 [▶]
  }

**Comment by Luceos** [comment]
So it's not setting up the tenant connection. That's weird. You really did this `dd()` inside the specific `routes.php` for this tenant? So under `storage/multi-tenant/.../routes.php` and not globally?

I did set up homestead as well now and it seems no database is created upon adding a tenant or running setup. I have to dig into that in order to get a solution.

**Comment by jartaud** [comment]
Yeah! i've created `storage/multi-tenant/tenant1/routes.php`

```
<?php

dd(DB::getConnections());

get('/myhome', ['uses' => '_507DirectoryLLC\Http\Controllers\HomeController@index','as' => 'myhome']);
```

**Comment by Luceos** [comment]
So then it must be the missing database in vagrant/homestead. I have my setup running to test this with an installation, I'll keep you up to date.

**Comment by jartaud** [comment]
Ubuntu 15  php5 + apache2

I'm missing something? I mean i'm pointing the hyn to the right database? should i set up a connection for each tenant (hyn1: databse->tenant1, hyn2: database->tenant3?  

`//database.php`

```
'mysql' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST', 'localhost'),
            'database'  => env('DB_DATABASE', 'forge'),
            'username'  => env('DB_USERNAME', 'forge'),
            'password'  => env('DB_PASSWORD', ''),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],

        'hyn' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST', 'localhost'),
            'database'  => env('DB_DATABASE', 'forge'),
            'username'  => env('DB_USERNAME', 'forge'),
            'password'  => env('DB_PASSWORD', ''),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
```

```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| MAIN_DB
| 1-tenant1       |
| 2-tenant2       |
| mysql              |
| performance_schema |
| wordpress          |
+--------------------+
9 rows in set (0.00 sec)

mysql> 
```

**Comment by Luceos** [comment]
No that should not be necessary. Hyn will automatically setup the connection to your database based on the current tenant.

So the databases are there, the TenantEnvironment is working, because your routes are available. Do you see any errors in your logs? Eg the log for the queue?

**Comment by jartaud** [comment]
Nope! I'm just getting a 3 seconds loop in my queries log:
2015-07-09 00:50:11 | select * from `hostnames` where `hostname` = NOTHING_IN_DB limit 1 | 0.6ms
2015-07-09 00:50:14 | select * from `hostnames` where `hostname` = NOTHING_IN_DB limit 1 | 0.6ms
2015-07-09 00:50:17 | select * from `hostnames` where `hostname` = NOTHING_IN_DB limit 1 | 0.6ms
....

**Comment by Luceos** [comment]
one last test: what does `dd(\App::make('tenant.hostname'));` say?

**Comment by Luceos** [comment]
that query might be from the queue is your tenant hostname actually in the `hyn.hostnames` table? Replace hyn with the database you set up for the hyn connection.

**Comment by jartaud** [comment]
I'll test tonight. But why checking for the hostnames in a job? When I go to http://tenant1.com the log shows ``select * from hostnames where hostname = tenant1.com limit 1 `` and ``select * from hostnames where hostname = tenant_fallback.com limit 1`` every 3 seconds.

**Comment by Luceos** [comment]
There is no need to run `dd(\App::make('tenant.hostname'));` in the job. Just exec it within a tenant controller. I'll need to delve into it to check up where it could have gone wrong. It might take some time, sorry.

**Comment by jartaud** [comment]
I'm not running ``dd(\App::make('tenant.hostname'))`` in a job, what i'm asking is why every 3 seconds i'm seeing in my queries log  these: ``select * from hostnames where hostname = tenant1.com limit 1`` and ``select * from hostnames where hostname = tenant_fallback.com limit 1``

**Comment by Luceos** [comment]
I'm not sure @jartaud is it part of a full backtrace or only this single line?

**Comment by jartaud** [comment]
Only the queries. In routes.php i'm calling : ``get_exe_queries();``

``
function get_exe_queries()
	{
        $request = app('request');
        $path = storage_path().'/logs/queries.log';

		DB::listen(
    		function ($sql, $bindings, $time) use($request, $path) {
    			
    			//$start = PHP_EOL.'=| '.$request->method().' '.$request->path().' |='.PHP_EOL;
    			//File::append($path, $start);
    			
    			$sql = str_replace(array('%', '?'), array('%%', '%s'), $sql);
    			$sql = vsprintf($sql, $bindings);
        		$time_now = (new DateTime())->format('Y-m-d H:i:s');
			    $log = $time_now.' | '.$sql.' | '.$time.'ms'.PHP_EOL;
			  	File::append($path, $log);
			  	
    		}
		);
	}
``

**Comment by Luceos** [comment]
Every time you see that, it's to identify the current hostname based on the request. That is not out of the normal. Otherwise hyn cannot identify the tenant website to show.

**Comment by Luceos** [comment]
this should be fixed, if not please post on https://github.com/lara-league/multi-tenant/issues
